#!/usr/bin/env bash

# ----------------------------------------------------------------------
# Filename:   Template 
# Version:    1.0
# Date:       2021/06/20
# Author:     Lz
# Email:      lz843723683@gmail.com
# History：     
#             Version 1.0, 2021/06/20
# Function:   Template 功能验证
# Out:        
#             0 => TPASS
#             1 => TFAIL
#             2 => TCONF
# ----------------------------------------------------------------------

# 测试主题
Title_Env_LTFLIB="测试模板"

# 本次测试涉及的命令
CmdsExist_Env_LTFLIB="Template"


## TODO : 个性化,初始化
#   Out : 0=>TPASS
#         1=>TFAIL
#         2=>TCONF
TestInit_LTFLIB(){
	return ${TPASS}
}


## TODO : 清理函数
#   Out : 0=>TPASS
#         1=>TFAIL
#         2=>TCONF
TestClean_LTFLIB(){
	return ${TPASS}
}


## TODO : 测试用例集
#   Out : 0=>TPASS
#         1=>TFAIL
#         2=>TCONF
Testsuite_LTFLIB(){
	testcase_1

	return $TPASS
}


## TODO : 测试用例
testcase_1(){
	Template
	CommRetParse_LTFLIB "Template" "true" "no"
}

#----------------------------------------------#

source "${LIB_LTFLIB}"
Main_LTFLIB $@
